disabled = false
languageCode = "ko-kr"     # 한국 코드로 변경
languageName = "한국어"      # 사이트상에 표시될 언어 이름
weight = 1
title = "Deep Dive Blog : Reinventing The Wheel"        # 블로그 제목

[params]
  displayName = "KO"
  isoCode = "ko"
  rtl = false
  dateFormat = "2006년 1월 2일" # 한국식 날짜 표기 (YYYY년 M월 D일)

  [params.author]
    name = "황인우"
    image = "img/author.jpg"
    headline = """
집착하는 개발자 황인우입니다.
E-MAIL : dlsdn1108@gmail.com
"""
    bio = """
안녕하세요. 문제 해결에 진심인 백엔드 개발자 황인우입니다.
E-MAIL : dlsdn1108@gmail.com
"""
    links = [
      { github = "https://github.com/iaminwoo" }
    ]