# -- Markup --
# These settings are required for the theme to function.

[goldmark]
  [goldmark.parser]
    wrapStandAloneImageWithinParagraph = false

    [goldmark.parser.attribute]
      block = true

  [goldmark.renderer]
    unsafe = true

  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true
      [goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)']]

[highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ""
  lineAnchors = ""
  lineNoStart = 1
  lineNos = true           # 코드 옆에 줄 번호 표시 (원치 않으면 false)
  lineNumbersInTable = true
  noClasses = true
  style = "github-dark"
  tabWidth = 4

[tableOfContents]
  startLevel = 2
  endLevel = 4
